version: '3'

services:
  mongodb:
    image: mongo:4.4-bionic
    container_name: mongodb-container
    ports:
      - 27019:27017
    volumes:
      - ./.data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: toDo
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwert

  golang-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb