version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: toDo
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwert

  golang-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb